---
name: Build and push docker images

env:
  DOCKERHUB_REPOSITORY: magnaz/transmission

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-push:
    name: Build image and push to DockerHub
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: magnaz
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set environment DOCKERHUB_IMAGES on "master" branch
        if: github.ref == 'refs/heads/master'
        run: echo "DOCKERHUB_IMAGES=${DOCKERHUB_REPOSITORY}:latest" >> $GITHUB_ENV
      - name: Set environment DOCKERHUB_IMAGES on "v*" branches
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKERHUB_IMAGES=${DOCKERHUB_REPOSITORY}:${GITHUB_REF_NAME},${DOCKERHUB_REPOSITORY}:${GITHUB_REF_NAME#v*}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKERHUB_IMAGES }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
